// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClQQwqF5FidwGVq5O4rUkyKbvS-efgRZc',
    appId: '1:575200019418:web:09d960da33ffd1064036e3',
    messagingSenderId: '575200019418',
    projectId: 'spa-app-e7bab',
    authDomain: 'spa-app-e7bab.firebaseapp.com',
    storageBucket: 'spa-app-e7bab.firebasestorage.app',
    measurementId: 'G-HZGY966XR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw2Y1b3MkhbeWTeqblqElKNbJYctR7200',
    appId: '1:575200019418:android:d264df42f97bd8b14036e3',
    messagingSenderId: '575200019418',
    projectId: 'spa-app-e7bab',
    storageBucket: 'spa-app-e7bab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSDFBV86BrW7rnzhEHbEC9Wa10sRA9pa4',
    appId: '1:575200019418:ios:562e1bae82f82b6e4036e3',
    messagingSenderId: '575200019418',
    projectId: 'spa-app-e7bab',
    storageBucket: 'spa-app-e7bab.firebasestorage.app',
    iosBundleId: 'com.example.spaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSDFBV86BrW7rnzhEHbEC9Wa10sRA9pa4',
    appId: '1:575200019418:ios:562e1bae82f82b6e4036e3',
    messagingSenderId: '575200019418',
    projectId: 'spa-app-e7bab',
    storageBucket: 'spa-app-e7bab.firebasestorage.app',
    iosBundleId: 'com.example.spaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClQQwqF5FidwGVq5O4rUkyKbvS-efgRZc',
    appId: '1:575200019418:web:dd934b62c7ec764d4036e3',
    messagingSenderId: '575200019418',
    projectId: 'spa-app-e7bab',
    authDomain: 'spa-app-e7bab.firebaseapp.com',
    storageBucket: 'spa-app-e7bab.firebasestorage.app',
    measurementId: 'G-BR4W3DSNX7',
  );
}
